name: build
on: 
  pull_request:
    paths:
      - '.github/workflows/build.yml'
      - 'src/**'
      - 'test/**'
      - 'package.json'
      - 'tsconfig.json'
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 24.x
          registry-url: https://registry.npmjs.org/
      - uses: pnpm/action-setup@v4
      
      - name: Install Dependencies
        run: pnpm install

      - name: Build Packages
        run: pnpm run build

      - name: Run Tests
        run: pnpm start
        working-directory: test